name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.19
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        if: hashFiles('**/*.{test,spec}.{js,jsx,ts,tsx}') != ''
        run: npm test -- --run
        env:
          CI: true
